version: 2
jobs:
    build:
        working_directory: ~/Breadcrumbs/
        docker:
            - image: circleci/openjdk:8u181-jdk
        steps:
            - checkout
            - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
                key: breadcrumbs-web-{{ checksum "web/pom.xml" }}
            - run: cd web && mvn dependency:go-offline # gets the project dependencies
            - save_cache:
                paths:
                    - ~/.m2
                key: breadcrumbs-web-{{ checksum "web/pom.xml" }}

            - run: cd web && mvn package
            - store_test_results:
                path: web/target/surefire-reports
            - store_artifacts:
                path: web/target/web-0.0.1-SNAPSHOT.jar
    deploy:
        machine:
            enabled: true
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "28:1d:02:09:d4:50:59:e3:de:1b:b4:97:30:7d:2b:51"
            - run:
                name: fix host authenticity for production server
                command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
            - run:
                name: Deploy Over SSH
                command: |
                   ssh -vv $SSH_USER@$SSH_HOST "<remote deploy command>"
            # - run:
            #     name: deploy app
            #     command: scp web/target/web-0.0.1-SNAPSHOT.jar $SSH_USERNAME@$SSH_HOST:test

        # machine:
        #     enabled: true
        # steps:
        #     - run:
        #         command: cat /home/circleci/.ssh/id_rsa
        #     - run:
        #         name: Deploy Over SSH
        #         command: |
        #            ssh -v $SSH_USER@$SSH_HOST "<remote deploy command>"
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
