version: 2
jobs:
    build:
        working_directory: ~/Breadcrumbs/web
        docker:
            - image: circleci/openjdk:8-jdk-browsers
        steps:
            - checkout:
                path: ~/Breadcrumbs/web
            - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
                key: breadcrumbs-web-{{ checksum "pom.xml" }}

            - run: mvn dependency:go-offline # gets the project dependencies

            - save_cache:
                paths:
                    - ~/.m2
                key: breadcrumbs-web-{{ checksum "pom.xml" }}

            - run: mvn package

            - store_test_results:
                path: target/surefire-reports

            - store_artifacts:
                path: target/web-0.0.1-SNAPSHOT.jar
